name: Setup
description: Setup Node.js, Bun, and install dependencies

runs:
  using: composite
  steps:
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version-file: .nvmrc

    - name: Setup Bun
      uses: oven-sh/setup-bun@v1
      with:
        bun-version: latest # or specify a version, e.g., '1.1.0'

    - name: Restore dependencies
      id: bun-cache
      uses: actions/cache/restore@v4
      with:
        path: |
          **/node_modules
          .bun/install-state.gz
        key: ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}-${{ hashFiles('**/package.json', '!node_modules/**') }}
        restore-keys: |
          ${{ runner.os }}-bun-${{ hashFiles('bun.lockb') }}
          ${{ runner.os }}-bun-

    - name: Install dependencies
      if: steps.bun-cache.outputs.cache-hit != 'true'
      run: bun install --immutable
      shell: bash

    - name: Cache dependencies
      if: steps.bun-cache.outputs.cache-hit != 'true'
      uses: actions/cache/save@v4
      with:
        path: |
          **/node_modules
          .bun/install-state.gz
        key: ${{ steps.bun-cache.outputs.cache-primary-key }}
